service: cc-technical-apw-lambda
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, dev}
  region: ${opt:region, self:custom.defaultRegion}
  profile: cc-tech-sls-admin

custom:
  defaultRegion: ap-southeast-2
  serverless-offline:
    allowCache: true

plugins:
  - serverless-plugin-typescript
  - serverless-offline