service: cc-tech-agw-lambda
frameworkVersion: '2'

provider:
  name: aws
  runtime: nodejs12.x
  stage: ${opt:stage, 'dev'}
  region: ${opt:region, self:custom.defaultRegion}
  profile: cc-tech-sls-admin

functions:
  authorizer:
    handler: 'src/handlers/authorizer.handler'
  list-ec2-sg:
    role: EC2FullReadAccessRole # We can either create a role or reference an existing one
    handler: 'src/handlers/list-ec2-sg.handler'
    memorySize: 256
    timeout: 20
    events:
      - http:
          method: GET
          path: '/list-ec2-sg'
          cors: true
          authorizer: authorizer

custom:
  defaultRegion: ap-southeast-2
  serverless-offline:
    allowCache: true

plugins:
  - serverless-dotenv-plugin
  - serverless-plugin-typescript
  - serverless-offline

resources:
  Resources:
    # https://docs.aws.amazon.com/apigateway/latest/developerguide/integrating-api-with-aws-services-lambda.html
    # Creates an EC2 readonly access role
    EC2FullReadAccessRole:
      Type: AWS::IAM::Role
      Properties:
        RoleName: ${self:service}-${self:provider.stage}-EC2FullReadAccessRole
        Description: Allows full read access to ec2
        AssumeRolePolicyDocument:
          Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Principal:
                Service:
                  - lambda.amazonaws.com
              Action: sts:AssumeRole
        Policies:
          - PolicyName: EC2FullReadAccess
            PolicyDocument:
              Version: '2012-10-17'
              Statement:
                # arn:aws:iam::aws:policy/AmazonEC2ReadOnlyAccess
                - Effect: Allow
                  Action:
                    - ec2:Describe*
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - elasticloadbalancing:Describe*
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - cloudwatch:ListMetrics
                    - cloudwatch:GetMetricStatistics
                    - cloudwatch:Describe*
                  Resource: '*'
                - Effect: Allow
                  Action:
                    - autoscaling:Describe*
                  Resource: '*'

                # Enable cloudwatch logs
                - Effect: Allow
                  Action:
                    - s3:PutObject
                    - logs:CreateLogStream
                    - logs:PutLogEvents
                  Resource: '*'
